# Generated by Django 4.2.7 on 2023-11-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
        ),
        migrations.AlterField(
            model_name='response',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.choice'),
        ),
    ]
