# Generated by Django 4.2.7 on 2023-11-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_choice_alter_response_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allResponses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='availableResponses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
